
[versions]
android-gradle-plugin = "8.3.2"
kotlin = "2.0.0"
androidx-core = "1.12.0"
androidx-lifecycle = "2.7.0"
androidx-activity-compose = "1.9.0"
androidx-compose-bom = "2024.04.01"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
androidx-test-espresso-core = "3.5.1"
firebase-bom = "33.1.0"
google-gms-services = "4.4.2"
androidx-navigation = "2.9.5"
androidx-lifecycle-runtime-compose = "2.9.4"
play-services-auth = "21.4.0"
play-services-games = "24.0.0"
appcompat = "1.6.1"
material = "1.10.0"
material3 = "1.4.0"
play-services-basement = "18.9.0"
foundation = "1.9.4"
firebase-messaging-ktx = "25.0.1"
retrofit = "2.9.0"
converter-gson = "2.9.0"
logging-interceptor = "4.10.0"
room-ktx = "2.8.4"
datastore-core = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-functions-ktx = { module = "com.google.firebase:firebase-functions-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso-core" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "androidx-navigation" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime-compose" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }
play-services-games = { group = "com.google.android.gms", name = "play-services-games", version.ref = "play-services-games" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
play-services-basement = { group = "com.google.android.gms", name = "play-services-basement", version.ref = "play-services-basement" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebase-messaging-ktx" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter-gson" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-ktx" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore-core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-gms-services" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
